- name: Update and Upgrade
  apt:
    update_cache: "yes"
    upgrade: "full"
  become: yes

- name: instal common package(Ubuntu)
  apt:
    name: "{{ install_packages }}"
    state: latest
  when:
    - ansible_distribution == "Ubuntu"
  become: yes

- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
  become: yes
